### ISSUE TITLE
Revit.Elements DetailCurve.ByCurve throws an input exception when used in Generic Detail Family

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoRevit#1644]
## Dynamo version

1.3

## Revit version

2017

## Operating system

Win 10

## What did you do? 

Attempted to create Detail Curves from Dynamo curves

## What did you expect to see?

The detail curves created in the Family document

## What did you see instead?
This:
![image](https://cloud.githubusercontent.com/assets/18601851/24921232/0abdcf56-1ee2-11e7-835a-16df4ddc39ef.png)

However, there's no reason why it should fail since my `CAD.DetailLinesFromCADLayers` node calls the same methods (`doc.FamilyCreate.NewDetailCurve()`) and works without issue:

![image](https://cloud.githubusercontent.com/assets/18601851/24921596/4517a98c-1ee3-11e7-8b47-63d1ba4032dc.png)

**Comment by sixtysecondrevit** [comment]
The node might be using Doc.Create instead of Doc.FamilyCreate? Clockworks has an if statement built in for this.
![image](https://cloud.githubusercontent.com/assets/15744724/24966647/cc308656-1f64-11e7-8e00-38e1b62aaaaf.png)

**Comment by ThomasMahon** [comment]
...In my original post:
> However, there's no reason why it should fail since my CAD.DetailLinesFromCADLayers node calls the same methods (doc.FamilyCreate.NewDetailCurve()) and works without issue:

Checking the source code of the [OOTB node](https://github.com/DynamoDS/DynamoRevit/blob/Revit2017/src/Libraries/RevitNodes/Elements/DetailCurve.cs) was the first thing I checked prior to posting to ensure I ruled out the obvious. Snippet from OOTB source: 
![image](https://cloud.githubusercontent.com/assets/18601851/24966902/2bc89406-1fa0-11e7-872b-17853713b9a8.png)

**Comment by ThomasMahon** [comment]
@mjkkirschner @aparajit-pratap I've done some more investigations and believe I've found the cause of the error: its either something wrong the View selection node or most likely the `Revit.Elements.Views.View.Sheet` class not inheriting from the abstract `View` class. 

**Reproducable error**
I can reproduce the same error in my `CAD.DetailLinesFromCADLayers` node by declaring the input view type as `Revit.Elements.Views.View`:
![image](https://cloud.githubusercontent.com/assets/18601851/24967716/f1a7e634-1fa2-11e7-992f-8b4dc06816a6.png)
![image](https://cloud.githubusercontent.com/assets/18601851/24967888/70a1b69a-1fa3-11e7-8e6a-dc3cd8918eb9.png)

**However**
When I use the `Element` superclass, it casts without issue and works as expected:
![image](https://cloud.githubusercontent.com/assets/18601851/24967475/22783206-1fa2-11e7-834b-68423dbd62f9.png)

![image](https://cloud.githubusercontent.com/assets/18601851/24967523/5027c496-1fa2-11e7-9fb0-1df6fdadbd1a.png)

Is this a bug?

**Comment by ksobon** [comment]
So this should be fixed now with this PR: https://github.com/DynamoDS/DynamoRevit/pull/1672
It was because `Sheet` was inheriting directly from the `Element` class, rather than from the `View` class.

**Comment by ThomasMahon** [comment]
Cheers. I'd be interested to know what the standards are for submitting PRs to the Dynamo GitHub - are there any resources or contacts I should speak to? I'll close this one out.

**Comment by ksobon** [comment]
Thanks for closing but I would wait until the PR gets accepted and merged. Until then I would keep it open.

**Comment by ThomasMahon** [comment]
@ksobon I think this is yet to be merged as its still an issue in 1.3.1. I'll reopen cc @aparajit-pratap @mjkkirschner
